export const STORE_OPTIONS = [
  "Abbotsford Volkswagen",
  "Acura of Hamilton",
  "Audi Windsor",
  "Audi Winnipeg",
  "BMW Laval",
  "BMW Montreal Centre",
  "Brantford Honda",
  "Bridges Chevrolet",
  "Cambridge Hyundai",
  "Capital Chrysler",
  "Courtesy Chrysler",
  "Crosstown Auto Centre",
  "Crowfoot Hyundai",
  "Dartmouth Dodge",
  "Dodge City Motors",
  "Eastern Chrysler",
  "Fish Creek Nissan",
  "Grande Prairie Chrysler",
  "Grande Prairie Hyundai",
  "Grande Prairie Nissan",
  "Grande Prairie Subaru",
  "Grande Prairie Volkswagen",
  "Guelph Hyundai",
  "Guelph Kia",
  "Hunt Club Nissan",
  "Hyatt Infiniti",
  "Island GM",
  "Kelleher Ford",
  "Kia of Hamilton",
  "London Honda",
  "London Infiniti",
  "London Kia",
  "Mann-Northway GM",
  "Maple Ridge Chrysler",
  "Maple Ridge GM",
  "Maple Ridge Volkswagen",
  "Mark Wilson's Better Used Cars",
  "McNaught Cadillac Buick GM",
  "Mercedes Benz Heritage Valley",
  "Mercedes Rive Sud",
  "Moncton Chrysler",
  "Northland Chrysler",
  "Northland Hyundai",
  "Northland Nissan",
  "Northland Volkswagen",
  "Nurse Chevrolet Cadillac LTD",
  "Parkland Dodge",
  "Planete Mazda",
  "Plaza Nissan",
  "Porsche Centre London",
  "Premier Chevrolet Cadillac Buick GMC",
  "Rose City Ford",
  "Saskatoon Motor Products",
  "Sherwood Park Hyundai",
  "Sherwood Park Volkswagen",
  "South London Nissan",
  "St. James Volkswagen",
  "Sterling Honda",
  "Subaru of Hamilton",
  "Tower Chrysler Dodge Jeep Ram",
  "Waterloo Honda",
  "Wellington Motors",
];